local M = {}

-- INSERT INTO npc VALUES (nextval('npc_seq'),0,-345,-441,0,4,false,'Hagar Wernson','npc_hagar_wernson.lua',0);

local autonpcfunctions = require("npc.base.autonpcfunctions")

function M.useNPC(user,counter,param)
    thisNPC:increaseSkill(1,"common language",100);
    thisNPC:talkLanguage(CCharacter.say, CPlayer.german, "Finger weg!");
    thisNPC:talkLanguage(CCharacter.say, CPlayer.english, "Don't you touch me!");
end

function M.initializeNpc()
    if TraderFirst then
        return true;
    end

    autonpcfunctions.InitTalkLists();

    -- ********* START DYNAMIC PART ********

    -- nordmark, in der taverne
    autonpcfunctions.AddTraderTrigger("gr[üue]+[sß]+e","Moin...Langohr");
    autonpcfunctions.AddAdditionalTrigger("Hallo");
    autonpcfunctions.AddAdditionalTrigger("Guten Tag");
    autonpcfunctions.AddAdditionalTrigger("Gruss");
    autonpcfunctions.AddAdditionalTrigger("Moin");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddCondition("chance",10 );
    autonpcfunctions.AddTraderTrigger("gr[üue]+[sß]+e","Moin...");
    autonpcfunctions.AddAdditionalTrigger("Hallo");
    autonpcfunctions.AddAdditionalTrigger("Guten Tag");
    autonpcfunctions.AddAdditionalTrigger("Gruss");
    autonpcfunctions.AddAdditionalTrigger("Moin");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddTraderTrigger("greetings","G'day...long-ear");
    autonpcfunctions.AddAdditionalTrigger("hello");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddCondition("chance",15 );
    autonpcfunctions.AddTraderTrigger("greetings","G'day...");
    autonpcfunctions.AddAdditionalTrigger("hello");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddTraderTrigger("gr[üue]+[sß]+e","Sei gegrüßt, holde Maid! Komm näher! Ich wisch auch den Tisch ab.");
    autonpcfunctions.AddAdditionalTrigger("Hallo");
    autonpcfunctions.AddAdditionalTrigger("Guten Tag");
    autonpcfunctions.AddAdditionalTrigger("Gruss");
    autonpcfunctions.AddAdditionalTrigger("Moin");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddTraderTrigger("greetings","G'day, beautyfull maiden! come here! I'll clean that table.");
    autonpcfunctions.AddAdditionalTrigger("hello");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddTraderTrigger("gr[üue]+[sß]+e","Moin, Moin, %CHARNAME! Komm ran! Hier kannste Dich vollkippen.");
    autonpcfunctions.AddCondition("item",7,"all",">=",1);
    autonpcfunctions.AddCondition("item",333,"all",">=",1);
    autonpcfunctions.AddAdditionalTrigger("Hallo");
    autonpcfunctions.AddAdditionalTrigger("Guten Tag");
    autonpcfunctions.AddAdditionalTrigger("Gruss");
    autonpcfunctions.AddAdditionalTrigger("Moin");
    autonpcfunctions.AddTraderTrigger("greetings","G'day, %CHARNAME! Here's yer place! Fill yer up?");
    autonpcfunctions.AddCondition("item",7,"all",">=",1);
    autonpcfunctions.AddCondition("item",333,"all",">=",1);
    autonpcfunctions.AddAdditionalTrigger("hello");
    autonpcfunctions.AddTraderTrigger("gr[üue]+[sß]+e","Moin, seid willkommen in der Drachentränke!");
    autonpcfunctions.AddAdditionalTrigger("Hallo");
    autonpcfunctions.AddAdditionalTrigger("Guten Tag");
    autonpcfunctions.AddAdditionalTrigger("Gruss");
    autonpcfunctions.AddAdditionalTrigger("Moin");
    autonpcfunctions.AddTraderTrigger("greetings","G'day, be wellcome in the Dragon's Pond!");
    autonpcfunctions.AddAdditionalTrigger("hello");
    autonpcfunctions.AddTraderTrigger("name","Es ist mir ein Vergnügen! Ich bin "..thisNPC.name..", der Wirt.");
    autonpcfunctions.AddCondition("lang","german");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddTraderTrigger("name","What a pleasure! I am "..thisNPC.name..", the innkeeper.");
    autonpcfunctions.AddCondition("lang","english");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddTraderTrigger("name","Ich bin "..thisNPC.name..", der Wirt.");
    autonpcfunctions.AddCondition("lang","german");
    autonpcfunctions.AddTraderTrigger("name","I am "..thisNPC.name..", the innkeeper.");
    autonpcfunctions.AddCondition("lang","english");
    autonpcfunctions.AddTraderTrigger("Was verkauft","Ich hab Jungfernglück, den beliebten Apfelwein, nur sechs Kupfer fürn Kelch. Wär das nix fuer Euch? Oder Gnollgift, den guten Rotwein, nur acht Kupfer. Bärenfalle, den besten Met auch für acht. Und Nordburger Schädelbrecher, unser Bier. Der Krug zu lumpigen acht Kupfer");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddTraderTrigger("Was kauft","Ich kauf Kupferkelche zurück, meine Liebe. Ein'n Kupfer fürn Kelch. Und Bierkruege, auch für'n Kupfer. Für graue Flaschen zahl ich zwei.");
    autonpcfunctions.AddAdditionalTrigger("Was kaufst");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddTraderTrigger("what sell","I got virgen's delight, our applewine, six copper the goblet. Specially for you, my dear. An' Gnollpoison, a red wine, or Beartrap, our meade, both for eight copper the goblet. An' Northburger scullcracker, our beer, for eight copper the mug.");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddTraderTrigger("what do buy","I buy back the empty mugs and coppergoblets, my dear. For a copper each. And grey bottles, for two copper each.");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddTraderTrigger("Was verkauft","Ich hab Jungfernglück, den beliebten Apfelwein, nur sechs Kupfer fürn Kelch. Oder Gnollgift, den guten Rotwein, nur acht Kupfer. Bärenfalle, den besten Met auch für acht. Und Nordburger Schädelbrecher, unser Bier. Der Krug  zu lumpigen acht Kupfer");
    autonpcfunctions.AddTraderTrigger("Was kauft","Ich kauf Kupferkelche zurück. Ein'n Kupfer fürn Kelch. Und Bierkruege, auch für'n Kupfer. Für graue Flaschen zahl ich zwei.");
    autonpcfunctions.AddAdditionalTrigger("Was kaufst");
    autonpcfunctions.AddTraderTrigger("what sell","I got virgen's delight, our applewine, six copper the goblet. An' Gnollpoison, a red wine, or Beartrap,  our meade, both for eight copper the goblet. An' Northburger scullcracker, our beer, for eight copper the mug.");
    autonpcfunctions.AddTraderTrigger("what do buy","I buy back the empty mugs and coppergoblets. For a copper each. And grey bottles, for two copper each.");
    autonpcfunctions.AddTraderTrigger("buy milk","Here is no monastery! get lost!");
    autonpcfunctions.AddTraderTrigger("milch kauf","Hier iss doch kein Kloster! Verschwinde!");
    autonpcfunctions.AddAdditionalTrigger("kauf milch");
    autonpcfunctions.AddTraderTrigger("buy water","ye can water yer cow outside! this ain't no stable here!");
    autonpcfunctions.AddTraderTrigger("wasser kauf","Deine Kuh kannst du draussen tränken! Dies iss doch kein Stall!");
    autonpcfunctions.AddAdditionalTrigger("kauf wasser");
    autonpcfunctions.AddTraderTrigger("buy a virgen's delight","Bugger off! We don't like beggars without money here!");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("buy a cyder");
    autonpcfunctions.AddCondition("money","<",6);
    autonpcfunctions.AddTraderTrigger("buy a virgen's delight","My dear, I cain't give yer a drink without money.");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("buy a cyder");
    autonpcfunctions.AddCondition("money","<",6);
    autonpcfunctions.AddTraderTrigger("buy a virgen's delight","Yer 'ave not enuff money, come back, when yer can pay.");
    autonpcfunctions.AddAdditionalTrigger("buy a cyder");
    autonpcfunctions.AddCondition("money","<",6);
    autonpcfunctions.AddTraderTrigger("buy a virgen's delight","Yer cyder. Gimme six copper.");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("buy a cyder");
    autonpcfunctions.AddConsequence("money","-",6);
    autonpcfunctions.AddConsequence("item",1844,1,333,0);
    autonpcfunctions.AddTraderTrigger("buy a virgen's delight","Here yer got it. Virgen's delight for the gracious maid!");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("buy a cyder");
    autonpcfunctions.AddConsequence("money","-",6);
    autonpcfunctions.AddConsequence("item",1844,1,333,0);
    autonpcfunctions.AddTraderTrigger("buy a virgen's delight","Here yer got it. drink, before the goblet gets rusty!");
    autonpcfunctions.AddAdditionalTrigger("buy a cyder");
    autonpcfunctions.AddConsequence("money","-",6);
    autonpcfunctions.AddConsequence("item",1844,1,333,0);
    autonpcfunctions.AddTraderTrigger("ein Apfelmost kauf","Mach das Du rauskommst! nich' bloss'n Elf, nee, auch noch'n Bettler! Also so was!");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("ein Apfelwein kauf");
    autonpcfunctions.AddAdditionalTrigger("ein Cider kauf");
    autonpcfunctions.AddAdditionalTrigger("ein Jungferngl[üue]+ck kauf");
    autonpcfunctions.AddCondition("money","<",6);
    autonpcfunctions.AddTraderTrigger("ein Apfelmost kauf","Ohne Kupfer kriegt selbst so'n hübsches Ding wie Du hier nix zu trinken!");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("ein Apfelwein kauf");
    autonpcfunctions.AddAdditionalTrigger("ein Cider kauf");
    autonpcfunctions.AddAdditionalTrigger("ein Jungferngl[üue]+ck kauf");
    autonpcfunctions.AddCondition("money","<",6);
    autonpcfunctions.AddTraderTrigger("ein Apfelmost kauf","Ohne Moos nix los! Komm wieder, wenn Du Geld hast!");
    autonpcfunctions.AddAdditionalTrigger("ein Apfelwein kauf");
    autonpcfunctions.AddAdditionalTrigger("ein Cider kauf");
    autonpcfunctions.AddAdditionalTrigger("ein Jungferngl[üue]+ck kauf");
    autonpcfunctions.AddCondition("money","<",6);
    autonpcfunctions.AddTraderTrigger("ein Apfelmost kauf","Ein Apfelwein. Sechs Kupfer.");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("ein Apfelwein kauf");
    autonpcfunctions.AddAdditionalTrigger("ein Cider kauf");
    autonpcfunctions.AddAdditionalTrigger("ein Jungferngl[üue]+ck kauf");
    autonpcfunctions.AddConsequence("money","-",6);
    autonpcfunctions.AddConsequence("item",1844,1,333,0);
    autonpcfunctions.AddTraderTrigger("ein Apfelmost kauf","Jungfernglück gestellt, vor die Dame hier von Welt!");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("ein Apfelwein kauf");
    autonpcfunctions.AddAdditionalTrigger("ein Cider kauf");
    autonpcfunctions.AddAdditionalTrigger("ein Jungferngl[üue]+ck kauf");
    autonpcfunctions.AddConsequence("money","-",6);
    autonpcfunctions.AddConsequence("item",1844,1,333,0);
    autonpcfunctions.AddTraderTrigger("ein Apfelmost kauf","Hier hast Du. Trink, bevor der Kelch rostet!");
    autonpcfunctions.AddAdditionalTrigger("ein Apfelwein kauf");
    autonpcfunctions.AddAdditionalTrigger("ein Cider kauf");
    autonpcfunctions.AddAdditionalTrigger("ein Jungferngl[üue]+ck kauf");
    autonpcfunctions.AddConsequence("money","-",6);
    autonpcfunctions.AddConsequence("item",1844,1,333,0);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER cyder","Wanna get more'n yer can pay, long-ear?  That ain't enuff money!");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER virgen's delight");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*6; end);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER cyder","That ain't enuff money, my dear, why don't yer take less?");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER virgen's delight");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*6; end);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER cyder","That ain't enuff money!");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER virgen's delight");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*6; end);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER cyder","Here are your %NUMBER cyder!");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER virgen's delight");
    autonpcfunctions.AddCondition("money",">=",function( a ) return a*6; end);
    autonpcfunctions.AddConsequence("money","-",function( a ) return a*6; end);
    autonpcfunctions.AddConsequence("item",1844,"%NUMBER",333,0);
    autonpcfunctions.AddTraderTrigger("%NUMBER Cider kauf","Na? Willst mehr saufen, als Du zahlen kannst, Langohr? Datt is nich genug Kupfer!");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Apfelmost kauf");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Apfelwein kauf");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Jungferngl[üue]+ck kauf");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*6; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER Cider kauf","Datt is nich genug Kupfer, meine Liebe. Nimm doch weniger.");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Apfelmost kauf");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Apfelwein kauf");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Jungferngl[üue]+ck kauf");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*6; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER Cider kauf","Datt is nich genug Kupfer!");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Apfelmost kauf");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Apfelwein kauf");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Jungferngl[üue]+ck kauf");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*6; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER Cider kauf","Hier hast du deine %NUMBER Apfelwein!");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Apfelmost kauf");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Apfelwein kauf");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Jungferngl[üue]+ck kauf");
    autonpcfunctions.AddCondition("money",">=",function( a ) return a*6; end);
    autonpcfunctions.AddConsequence("money","-",function( a ) return a*6; end);
    autonpcfunctions.AddConsequence("item",1844,"%NUMBER",333,0);
    autonpcfunctions.AddTraderTrigger("buy a beer","Bugger off! We don't like beggars without money here!");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("buy a scullcracker");
    autonpcfunctions.AddTraderTrigger("buy a beer","My dear, I cain't give yer a drink without money.");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("buy a scullcracker");
    autonpcfunctions.AddTraderTrigger("buy a beer","Yer 'ave not enuff money, come back, when yer can pay.");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddAdditionalTrigger("buy a scullcracker");
    autonpcfunctions.AddTraderTrigger("buy a beer","Yer beer. Gimme eight copper.");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("buy a scullcracker");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1909,1,333,0);
    autonpcfunctions.AddTraderTrigger("buy a beer","Here yer got it. a scullcracker for the daring gal! that'll give yer more headaches than a husband!");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("buy a scullcracker");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1909,1,333,0);
    autonpcfunctions.AddTraderTrigger("buy a beer","Here yer got it. drink, before it cools down!");
    autonpcfunctions.AddAdditionalTrigger("buy a scullcracker");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1909,1,333,0);
    autonpcfunctions.AddTraderTrigger("ein bier kauf","Mach das Du rauskommst! nich' bloss'n Elf, nee, auch noch'n Bettler! Also so was!");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("ein sch[äae]+delbrecher kauf");
    autonpcfunctions.AddTraderTrigger("ein bier kauf","Ohne Kupfer kriegt selbst so'n hübsches Ding wie Du hier nix zu trinken!");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("ein sch[äae]+delbrecher kauf");
    autonpcfunctions.AddTraderTrigger("ein bier kauf","Ohne Kohle kein Bier! Komm wieder, wenn Du Geld hast!");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddAdditionalTrigger("ein sch[äae]+delbrecher kauf");
    autonpcfunctions.AddTraderTrigger("ein bier kauf","Ein Bier. Acht Kupfer.");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("ein sch[äae]+delbrecher kauf");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1909,1,333,0);
    autonpcfunctions.AddTraderTrigger("ein bier kauf","Den Schädelbrecher der Herzensbrecherin!");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("ein sch[äae]+delbrecher kauf");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1909,1,333,0);
    autonpcfunctions.AddTraderTrigger("ein bier kauf","Hier hast es. Trink, bevor es kalt wird!");
    autonpcfunctions.AddAdditionalTrigger("ein sch[äae]+delbrecher kauf");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1909,1,333,0);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER beer","Wanna get more'n yer can pay, long-ear?  That ain't enuff money!");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER scullcracker");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER beer","That ain't enuff money, my dear, why don't yer take less?");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER scullcracker");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER beer","That ain't enuff money!");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER scullcracker");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER beer","Here are your %NUMBER beer!");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER scullcracker");
    autonpcfunctions.AddCondition("money",">=",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("money","-",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("item",1909,"%NUMBER",333,0);
    autonpcfunctions.AddTraderTrigger("%NUMBER Bier kauf","Na? Willst mehr saufen, als Du zahlen kannst, Langohr? Datt is nich genug Kupfer!");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("%NUMBER sch[äae]+delbrecher kauf");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER bier kauf","Datt is nich genug Kupfer, meine Liebe. Nimm doch weniger.");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER sch[äae]+delbrecher kauf");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER bier kauf","Datt is nich genug Kupfer!");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER sch[äae]+delbrecher kauf");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER bier kauf","Hier hast du deine %NUMBER Bier!");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER sch[äae]+delbrecher kauf");
    autonpcfunctions.AddCondition("money",">=",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("money","-",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("item",1909,"%NUMBER",333,0);
    autonpcfunctions.AddTraderTrigger("buy a wine","Bugger off! We don't like beggars without money here!");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("buy a gnollpoison");
    autonpcfunctions.AddTraderTrigger("buy a wine","My dear, I cain't give yer a drink without money.");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("buy a gnollpoison");
    autonpcfunctions.AddTraderTrigger("buy a wine","Yer 'ave not enuff money, come back, when yer can pay.");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddAdditionalTrigger("buy a gnollpoison");
    autonpcfunctions.AddTraderTrigger("buy a wine","Yer wine. Gimme eight copper.");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("buy a gnollpoison");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1842,1,333,0);
    autonpcfunctions.AddTraderTrigger("buy a wine","Here yer got it. Gnollpoison for the beauty! that's good for yer skin!");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("buy a gnollpoison");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1842,1,333,0);
    autonpcfunctions.AddTraderTrigger("buy a wine","Here yer got it. drink, before the gnolls come for it!");
    autonpcfunctions.AddAdditionalTrigger("buy a gnollpoison");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1842,1,333,0);
    autonpcfunctions.AddTraderTrigger("ein Wein kauf","Mach das Du rauskommst! nich' bloss'n Elf, nee, auch noch'n Bettler! Also so was!");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("ein Gnollgift kauf");
    autonpcfunctions.AddTraderTrigger("ein Wein kauf","Ohne Kupfer kriegt selbst so'n strammes Weib wie Du hier nix zu trinken!");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("ein Gnollgift kauf");
    autonpcfunctions.AddTraderTrigger("ein Wein kauf","Ohne Kupfer keinen Wein! Komm wieder, wenn Du Geld hast!");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddAdditionalTrigger("ein Gnollgift kauf");
    autonpcfunctions.AddTraderTrigger("ein Wein kauf","Ein Wein. Acht Kupfer.");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("ein Gnollgift kauf");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1842,1,333,0);
    autonpcfunctions.AddTraderTrigger("ein Wein kauf","Das Gnollgift für die Hübsche! Der iss gut für die Haut.");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("ein Gnollgift kauf");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1842,1,333,0);
    autonpcfunctions.AddTraderTrigger("ein Wein kauf","Hier hast ihn. Trink, wenn Du kein Gnoll bist!");
    autonpcfunctions.AddAdditionalTrigger("ein Gnollgift kauf");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1842,1,333,0);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER wine","Wanna get more'n yer can pay, long-ear?  That ain't enuff money!");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER gnollpoison");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER wine","That ain't enuff money, my dear, why don't yer take less?");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER gnollpoison");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER wine","That ain't enuff money!");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER gnollpoison");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER wine","Here are your %NUMBER wine!");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER gnollpoison");
    autonpcfunctions.AddCondition("money",">=",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("money","-",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("item",1842,"%NUMBER",333,0);
    autonpcfunctions.AddTraderTrigger("%NUMBER Wein kauf","Na? Willst mehr saufen, als Du zahlen kannst, Langohr? Datt is nich genug Kupfer!");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Gnollgift kauf");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER Wein kauf","Datt is nich genug Kupfer, meine Teuerste. Nimm doch weniger.");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Gnollgift kauf");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER Wein kauf","Datt is nich genug Kupfer!");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Gnollgift kauf");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER Wein kauf","Hier hast du deine %NUMBER Weine!");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER Gnollgift kauf");
    autonpcfunctions.AddCondition("money",">=",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("money","-",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("item",1842,"%NUMBER",333,0);
    autonpcfunctions.AddTraderTrigger("buy a meade","Bugger off! We don't like beggars without money here!");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("buy a beartrap");
    autonpcfunctions.AddTraderTrigger("buy a meade","Honey, I cain't give yer a drink without money.");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("buy a beartrap");
    autonpcfunctions.AddTraderTrigger("buy a meade","Yer 'ave not enuff money, come back, when yer can pay.");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddAdditionalTrigger("buy a beartrap");
    autonpcfunctions.AddTraderTrigger("buy a meade","Yer meade. Eight copper.");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("buy a beartrap");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1843,1,333,0);
    autonpcfunctions.AddTraderTrigger("buy a meade","Here it is. As sweet, as ye are!");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("buy a beartrap");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1843,1,333,0);
    autonpcfunctions.AddTraderTrigger("buy a meade","Here yer meade. Sweet, sticky ann' strong!");
    autonpcfunctions.AddAdditionalTrigger("buy a beartrap");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1843,1,333,0);
    autonpcfunctions.AddTraderTrigger("ein Met kauf","Mach das Du rauskommst! nich' bloss'n Elf, nee, auch noch'n Bettler! Also so was!");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("ein B[äae]+renfalle kauf");
    autonpcfunctions.AddTraderTrigger("ein Met kauf","Ohne Kupfer kriegt nich ma' so'n süßes Mädel wie Du hier watt zu trinken!");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("ein B[äae]+renfalle kauf");
    autonpcfunctions.AddTraderTrigger("ein Met kauf","Ohne Kupfer keinen Met! Komm wieder, wenn Du Dir das Saufen leisten kannst!");
    autonpcfunctions.AddCondition("money","<",8);
    autonpcfunctions.AddAdditionalTrigger("ein B[äae]+renfalle kauf");
    autonpcfunctions.AddTraderTrigger("ein Met kauf","Ein Met. Acht Kupfer.");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("ein B[äae]+renfalle kauf");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1843,1,333,0);
    autonpcfunctions.AddTraderTrigger("ein Met kauf","Ein Met für die Holde! Der iss fast so süss, wie Du!");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("ein B[äae]+renfalle kauf");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1843,1,333,0);
    autonpcfunctions.AddTraderTrigger("ein Met kauf","Hier hast ihn. Kipp weg, eh die Fliegen dran kleben!");
    autonpcfunctions.AddAdditionalTrigger("ein B[äae]+renfalle kauf");
    autonpcfunctions.AddConsequence("money","-",8);
    autonpcfunctions.AddConsequence("item",1843,1,333,0);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER beartrap","Wanna get more'n yer can pay, long-ear?  That ain't enuff money!");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER meade");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER beartrap","That ain't enuff money, my beauty, why don't yer take less?");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER meade");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER beartrap","That ain't enuff money!");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER meade");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("buy %NUMBER beartrap","Here are your %NUMBER meade!");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER meade");
    autonpcfunctions.AddCondition("money",">=",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("money","-",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("item",1843,"%NUMBER",333,0);
    autonpcfunctions.AddTraderTrigger("%NUMBER Met kauf","Na? Willst nich alles zahlen,watt Du saufen willst, Langohr? Datt is nich genug Kupfer!");
    autonpcfunctions.AddCondition("race", CCharacter.elf);
    autonpcfunctions.AddAdditionalTrigger("%NUMBER B[äae]+renfalle kauf");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER Met kauf","Datt Kupfer reicht nich, meine Süsse. Nimm doch weniger.");
    autonpcfunctions.AddCondition("sex","female");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER B[äae]+renfalle kauf");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER Met kauf","Datt is zu wenig Kupfer!");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER B[äae]+renfalle kauf");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER Met kauf","Hier hast du deine %NUMBER Met!");
    autonpcfunctions.AddAdditionalTrigger("%NUMBER B[äae]+renfalle kauf");
    autonpcfunctions.AddCondition("money",">=",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("money","-",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("item",1843,"%NUMBER",333,0);
    autonpcfunctions.AddTraderTrigger("%NUMBER goblet sale","That ain't so many!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER goblet");
    autonpcfunctions.AddCondition("item",1840,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER goblet sale","Here's yer money!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER goblet");
    autonpcfunctions.AddCondition("item",1840,"all",">=","%NUMBER");
    autonpcfunctions.AddConsequence("money","+","%NUMBER");
    autonpcfunctions.AddConsequence("deleteitem",1840,"%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER mug sale","That ain't so many!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER mug");
    autonpcfunctions.AddCondition("item",1908,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER mug sale","Here's yer money!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER mug");
    autonpcfunctions.AddCondition("item",1908,"all",">=","%NUMBER");
    autonpcfunctions.AddConsequence("money","+","%NUMBER");
    autonpcfunctions.AddConsequence("deleteitem",1908,"%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER kelch verkauf","Datt sind weniger!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER kelch");
    autonpcfunctions.AddCondition("item",1840,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER kelch verkauf","Hier is datt Geld!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER kelch");
    autonpcfunctions.AddCondition("item",1840,"all",">=","%NUMBER");
    autonpcfunctions.AddConsequence("money","+","%NUMBER");
    autonpcfunctions.AddConsequence("deleteitem",1840,"%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER krug verkauf","Datt sind weniger!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER krug");
    autonpcfunctions.AddCondition("item",1908,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER krug verkauf","Hier is datt Geld!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER krug");
    autonpcfunctions.AddCondition("item",1908,"all",">=","%NUMBER");
    autonpcfunctions.AddConsequence("money","+","%NUMBER");
    autonpcfunctions.AddConsequence("deleteitem",1908,"%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER grey bottle sale","That ain't so many!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER grey bottle");
    autonpcfunctions.AddCondition("item",2498,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER grey bottle sale","Here's yer money!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER grey bottle");
    autonpcfunctions.AddCondition("item",2498,"all",">=","%NUMBER");
    autonpcfunctions.AddConsequence("money","+",function( a ) return a*2; end);
    autonpcfunctions.AddConsequence("deleteitem",2498,"%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER grey bottle buy","That ain't enuff money!");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER grey bottle");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER grey bottle buy","I ain't got so many!");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER grey bottle");
    autonpcfunctions.AddCondition("number",">",10);
    autonpcfunctions.AddTraderTrigger("%NUMBER grey bottle buy","Here ye got yer %NUMBER bottles!");
    autonpcfunctions.AddAdditionalTrigger("buy %NUMBER grey bottle");
    autonpcfunctions.AddCondition("money",">=",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("money","-",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("item",2498,"%NUMBER",333,0);
    autonpcfunctions.AddTraderTrigger("%NUMBER grau flasche verkauf","Datt sind weniger!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER grau flasche");
    autonpcfunctions.AddCondition("item",2498,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER grau flasche verkauf","Hier is datt Geld!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER grau flasche");
    autonpcfunctions.AddCondition("item",2498,"all","<","%NUMBER");
    autonpcfunctions.AddConsequence("money","+","%NUMBER");
    autonpcfunctions.AddConsequence("deleteitem",2498,"%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER grau flasche kauf","Datt kost' mehr!");
    autonpcfunctions.AddAdditionalTrigger("kauf %NUMBER grau flasche");
    autonpcfunctions.AddCondition("money","<",function( a ) return a*8; end);
    autonpcfunctions.AddTraderTrigger("%NUMBER grau flasche kauf","So viel hab ich nich!");
    autonpcfunctions.AddAdditionalTrigger("kauf %NUMBER grau flasche");
    autonpcfunctions.AddCondition("number",">",10);
    autonpcfunctions.AddTraderTrigger("%NUMBER grau flasche kauf","Hier hast du deine %NUMBER Flaschen!");
    autonpcfunctions.AddAdditionalTrigger("kauf %NUMBER grau flasche");
    autonpcfunctions.AddCondition("money",">=",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("money","-",function( a ) return a*8; end);
    autonpcfunctions.AddConsequence("item",2498,"%NUMBER",333,0);
    autonpcfunctions.AddTraderTrigger("%NUMBER green bottle sale","That ain't so many!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER green bottle");
    autonpcfunctions.AddCondition("item",2499,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER green bottle sale","Here's yer money!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER green bottle");
    autonpcfunctions.AddCondition("item",2499,"all",">=","%NUMBER");
    autonpcfunctions.AddConsequence("money","+",function( a ) return a*9; end);
    autonpcfunctions.AddConsequence("deleteitem",2499,"%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER black bottle sale","That ain't so many!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER black bottle");
    autonpcfunctions.AddCondition("item",2501,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER black bottle sale","Here's yer money!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER black bottle");
    autonpcfunctions.AddCondition("item",2501,"all",">=","%NUMBER");
    autonpcfunctions.AddConsequence("money","+",function( a ) return a*10; end);
    autonpcfunctions.AddConsequence("deleteitem",2501,"%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER red bottle sale","That ain't so many!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER red bottle");
    autonpcfunctions.AddCondition("item",2500,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER red bottle sale","Here's yer money!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER red bottle");
    autonpcfunctions.AddCondition("item",2500,"all","<","%NUMBER");
    autonpcfunctions.AddConsequence("money","+",function( a ) return a*11; end);
    autonpcfunctions.AddConsequence("deleteitem",2500,"%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER orange bottle sale","That ain't so many!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER orange bottle");
    autonpcfunctions.AddCondition("item",2497,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER orange bottle sale","Here's yer money!");
    autonpcfunctions.AddAdditionalTrigger("sell %NUMBER orange bottle");
    autonpcfunctions.AddCondition("item",2497,"all",">=","%NUMBER");
    autonpcfunctions.AddConsequence("money","+",function( a ) return a*12; end);
    autonpcfunctions.AddConsequence("deleteitem",2497,"%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER gruen flasche verkauf","Du hast ja garnich so viel!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER gruen flasche");
    autonpcfunctions.AddCondition("item",2499,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER gruen flasche verkauf","Hier is datt Geld!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER gruen flasche");
    autonpcfunctions.AddCondition("item",2499,"all","<","%NUMBER");
    autonpcfunctions.AddConsequence("money","+",function( a ) return a*9; end);
    autonpcfunctions.AddConsequence("deleteitem",2499,"%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER schwarz flasche verkauf","Du hast ja garnich so viel!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER schwarz flasche");
    autonpcfunctions.AddCondition("item",2501,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER schwarz flasche verkauf","Hier is datt Geld!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER schwarz flasche");
    autonpcfunctions.AddCondition("item",2501,"all",">=","%NUMBER");
    autonpcfunctions.AddConsequence("money","+",function( a ) return a*10; end);
    autonpcfunctions.AddConsequence("deleteitem",2501,"%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER rot flasche verkauf","Du hast ja garnich so viel!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER rot flasche");
    autonpcfunctions.AddCondition("item",2500,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER rot flasche verkauf","Hier is datt Geld!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER rot flasche");
    autonpcfunctions.AddCondition("item",2500,"all",">=","%NUMBER");
    autonpcfunctions.AddConsequence("money","+",function( a ) return a*11; end);
    autonpcfunctions.AddConsequence("deleteitem",2500,"%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER orange flasche verkauf","Du hast ja garnich so viel!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER orange flasche");
    autonpcfunctions.AddCondition("item",2497,"all","<","%NUMBER");
    autonpcfunctions.AddTraderTrigger("%NUMBER orange flasche verkauf","Hier is datt Geld!");
    autonpcfunctions.AddAdditionalTrigger("verkauf %NUMBER orange flasche");
    autonpcfunctions.AddCondition("item",2497,"all","<","%NUMBER");
    autonpcfunctions.AddConsequence("money","+",function( a ) return a*12; end);
    autonpcfunctions.AddConsequence("deleteitem",2497,"%NUMBER");
    autonpcfunctions.AddTraderTrigger(" sale","I don't buy that!");
    autonpcfunctions.AddAdditionalTrigger("sell ");
    autonpcfunctions.AddTraderTrigger(" buy","I don't sell that!");
    autonpcfunctions.AddAdditionalTrigger("buy ");
    autonpcfunctions.AddTraderTrigger(" verkauf","Das kauf ich nicht!");
    autonpcfunctions.AddAdditionalTrigger("verkauf ");
    autonpcfunctions.AddTraderTrigger(" kauf","So was verkauf ich nicht!");
    autonpcfunctions.AddAdditionalTrigger("kauf ");
    autonpcfunctions.AddTraderTrigger("auf bald","Bis bald! Und lass dir nich auffe Hände treten...");
    autonpcfunctions.AddAdditionalTrigger("bis bald");
    autonpcfunctions.AddAdditionalTrigger("tschüss");
    autonpcfunctions.AddTraderTrigger("farewell","Be well! An' carefull, that no one steps on yer hands...");
    autonpcfunctions.AddAdditionalTrigger("bye");
    autonpcfunctions.AddAdditionalTrigger("good day");
    autonpcfunctions.AddCycleText("wir laaagen vor Sor-Ann-Araah... und hatten 'nen Elf ahan Bord....  In den Kesseln da faulte das Wassah...  da soffen wir Bier soohofort... ","Blow wi-ind, blow... to Salkamar we go.... her hair was blond her eyes were blue... her lips were red, her axe was new... ter my hodae, ter my hodae, ter my hodae, hodae ho!");
    autonpcfunctions.AddCycleText("#me verwischt den Dreck auf dem Tisch","#me wipes in the dirt on the table");
    autonpcfunctions.AddCycleText("#me steht in einer Wolke übler Gerüche","#me stands in a cloud of bad smells");
    autonpcfunctions.AddCycleText("#me trocknet einen Krug mit einem Drecklappen","#me dries a mug with a dirty rag");
    autonpcfunctions.AddCycleText("#me klaubt sich Krümel aus dem Bart","#me picks crumbs out of his beard");
    autonpcfunctions.AddCycleText("#me pustet den Staub aus einem Bierkrug","#me blows dust out of a mug");
    autonpcfunctions.AddCycleText("#me reisst sich Haare aus der Nase","#me picks hair out of his nose");
    autonpcfunctions.AddCycleText("Von den blauen Wellen kommen wir!... unser Käpt'n iss so blöd wie wir!... an den Rudern unsrer Boote, krieg'n wir Blasen anner Pfote.... von den blauen Wellen kommen wir!...","oh beat the drum slowly, an' play the flute only, as they carry me along... cause I'm a young pirate, an' I surely done wrong...");
    autonpcfunctions.AddCycleText("#me riecht nach vergammeltem Fleisch und feuchtem Schafsfell","#me smells of putrefied meat and wet sheepskin");
    autonpcfunctions.AddCycleText("#me kratzt sich abwesend unterm Kilt","#me scratches himself below his kilt absently");
    autonpcfunctions.AddCycleText("#me sieht sich gelangweilt um","#me looks around bored");
    autonpcfunctions.AddCycleText("#me trocknet sich mit dem Geschirrtuch unter den Achseln","#me dries his armpits with the dishrag");
    autonpcfunctions.AddCycleText("#me's Atem riecht nach schalem Bier","#me's breath smells of stale beer");
    -- dank an Dariya fuer einige eklige ideen
    -- von kormkormsen fuer Illarion 
    -- ********* END DYNAMIC PART ********
    TradSpeakLang={0,1};
    TradStdLang=0;

    autonpcfunctions.increaseLangSkill(TradSpeakLang);
    thisNPC.activeLanguage=TradStdLang;

end

function M.nextCycle()  -- ~10 times per second
    M.initializeNpc();
    autonpcfunctions.SpeakerCycle();
end

function M.receiveText(texttype, message, originator)
    if autonpcfunctions.BasicNPCChecks(originator,2) then
        if autonpcfunctions.LangOK(originator,TradSpeakLang) then
            autonpcfunctions.TellSmallTalk(message,originator);
        else
            autonpcfunctions.Confused(
               "#me sieht dich leicht verwirrt an",
               "#me looks at you a little confused"
            );
        end
    end
end

return M
